target 'ABFRealmSearchViewControllerExample' do
  pod 'Realm', '>=0.100.0'
  pod 'RealmSFRestaurantData'
  pod 'TOWebViewController'
end

target 'ABFRealmSearchViewControllerExampleTests' do
  pod 'Realm/Headers', '>=0.100.0'
end

